# Generated by Django 4.1.5 on 2023-02-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birth_date_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile-pic.png', null=True, upload_to='profile-pics/'),
        ),
    ]
