# Generated by Django 4.1.7 on 2023-03-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
