# Generated by Django 4.1.7 on 2023-03-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usergroup_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
