# Generated by Django 4.1.7 on 2023-04-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
