# Generated by Django 4.1.5 on 2023-02-07 19:47

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, default='default-profile-pic.png', null=True, upload_to='event-banners/'),
        ),
    ]
