# Generated by Django 4.1.7 on 2023-03-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_alter_user_friends'),
        ('events', '0006_alter_event_location_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usergroup'),
        ),
    ]
