# Generated by Django 4.1.7 on 2023-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='access',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('O', 'Open'), ('P', 'Private'), ('G', 'Group')], default='O', max_length=1),
        ),
    ]
