version: '3.8'

services:
    postgres_db:
        image: postgres:15.1
        container_name: postgres_db
        restart: on-failure
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/posgresql/data
        ports:
            - 5432:5423

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:6
        restart: unless-stopped
        env_file:
            - .env
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        depends_on:
            - postgres_db
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        ports:
            - 8080:80

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        environment:
            - WAIT_HOSTS=postgres_db
            - DATABASE_URL=postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres_db/${POSTGRES_DB}
        volumes:
            - .:/app
        depends_on:
            - postgres_db
            - pgadmin
        restart: on-failure

volumes:
    db_data:
        driver: local
    pgadmin-data:
        driver: local
