# Generated by Django 4.1.7 on 2023-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0002_message_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('thread__isnull', False), ('receiver__isnull', True)), models.Q(('thread__isnull', True), ('receiver__isnull', False)), _connector='OR'), name='thread_or_receiver_set'),
        ),
    ]
