# Generated by Django 4.1.7 on 2023-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0003_message_thread_or_receiver_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='deleted_by_receiver',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(('thread__isnull', True), ('deleted_by_receiver__isnull', True), _connector='OR'), name='deleted_by_receiver_null_when_thread_present'),
        ),
    ]
