# Generated by Django 4.1.7 on 2023-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0004_alter_message_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='deleted_by_receiver',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
