# Generated by Django 4.1.7 on 2023-03-20 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagebox', '0005_alter_message_deleted_by_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='deleted_by_users',
            field=models.ManyToManyField(related_name='deleted_message_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
