# Generated by Django 4.1.7 on 2023-03-20 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagebox', '0006_messagethread_deleted_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='deleted_by_users',
            field=models.ManyToManyField(blank=True, related_name='deleted_message_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
