# Generated by Django 4.1.7 on 2023-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0007_alter_messagethread_deleted_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='name',
            field=models.CharField(default='def', max_length=50),
        ),
    ]
