# Generated by Django 4.1.7 on 2023-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0008_messagethread_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
