# Generated by Django 4.1.7 on 2023-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0010_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='deleted_by_receiver',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
